### ISSUE TITLE
Fehler beim Versenden des Ladestatus mit amtron-out

### ISSUE THREAD

**Issue by ecar2022** [msob/NodeRedContribAmtronWallbox#1]
Das Auslesen der der Wallbox mit amtron-in funktioniert hervorragend. Bein setzten des Registers 41026 "Change charge state""Pause" 1 oder "Continue" 2 stürzt Node Red ab und auch die Wallbox wertet den Befehl nicht aus.

**Comment by msob** [comment]
Hallo ecar2022!

Ich verwende genau die Register ohne Probleme.

Welche Software ist auf dem AMTRON installiert und ist die Out-Node richtig konfiguriert?

**Comment by ecar2022** [comment]
Hallo,
auf der AMTRON ist die Firmeware 1.13 installiert. Die Out Node hat die richtige IP Adresse und ich habe das richtige Register ausgewählt. Mehr Konfigurationsmöglichkeiten habe ich nicht gesehen. 

Node Red ist als Docker Container installiert und läuft gut!

**Comment by msob** [comment]
Ich habe etra ein Test-Setup aufgebaut, aber die Node funktioniert bei mir.

Welcher Wert wird denn in der msg.payload an die Node übergeben?
Kannst du evtl. mal einen Minimal-Flow mit zwei Nodes ausprobieren?

**Comment by ecar2022** [comment]
Hallo, ich habe es einmal mit einer Zahl "2" für Continue und einmal als Textvariable übergeben! Funktionierte beides nicht!

**Comment by msob** [comment]
Dass der AMTRON einen Befehl nicht annimmt wäre das eine, aber dass er ihn nicht annimmt, weil Node RED abstürzt, ist mehr als ungewöhnlich.

Falls ich dir helfen kann, brauche ich dafür noch mehr Informationen. 

- Funktioniert die AMTRON Out Node mit einem anderen Register?
- Welche Node-RED Version benutzt du?
- Welche Version von amtron-wallbox hast du installiert?
- Auf welchem Weg hast du die AMTRON Nodes installiert?
- Verwendest du ein öffentliches Docker-Image und wenn ja, welches?
- Auf was für einem System läuft der Docker Container (welches Windows/Linux, auf PC oder einem ARM-System)?
- Bitte poste mal einen Flow-Export mit einem Minimal-Beispiel, damit ich mir das ansehen kann.

**Comment by ecar2022** [comment]
•	Funktioniert die AMTRON Out Node mit einem anderen Register?
o	Habe ich noch nicht getestet.

•	Welche Node-RED Version benutzt du?
o	Node-RED version: v2.2.2
o	Node.js  version: v14.18.2
o	Linux 5.10.102.1-microsoft-standard-WSL2 x64 LE

•	Welche Version von amtron-wallbox hast du installiert?
o	AMTRON® Xtra

•	Auf welchem Weg hast du die AMTRON Nodes installiert?
o	Installation über Node Red, Erweitung Palette verwalten , Amtron …

•	Verwendest du ein öffentliches Docker-Image und wenn ja, welches?
o	Docker Desktop 4.9.1 (81317) is currently the newest version available.

•	Auf was für einem System läuft der Docker Container (welches Windows/Linux, auf PC oder einem ARM-System)?
o	Windows 11 (Entwicklungsumgebung, Umzug auf Raspberry PI vorgesehen!)
o	Node-RED version: v2.2.2
o	Node.js  version: v14.18.2
o	Linux 5.10.102.1-microsoft-standard-WSL2 x64 LE

•	Bitte poste mal einen Flow-Export mit einem Minimal-Beispiel, damit ich mir das ansehen kann.
o	Einmal ein Test Flow mit einem Inject und amtron-out
[
    {
        "id": "1b8c8cdb0abe5234",
        "type": "tab",
        "label": "Test",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "05f9a73d70efb414",
        "type": "inject",
        "z": "1b8c8cdb0abe5234",
        "name": "Pause beenden",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "2",
        "payloadType": "num",
        "x": 200,
        "y": 140,
        "wires": [
            [
                "c6781059e863b448"
            ]
        ]
    },
    {
        "id": "c6781059e863b448",
        "type": "amtron-out",
        "z": "1b8c8cdb0abe5234",
        "name": "AMTRON out",
        "ip": "192.168.2.139",
        "register": "HR_0x0401_UINT16",
        "x": 460,
        "y": 140,
        "wires": []
    }
]

**Comment by msob** [comment]
Ich habe mir mit den Angaben eine komplett neue Umgebung eingerichtet, unter Windows, mit WSL2 und Docker Desktop. Ich habe den offiziellen Node-RED Container benutzt, mit Node-RED 2.2.2 (Docker Image nodered/node-red:2.2.2) und NodeJS 14.18.2.

Ich habe die AMTRON-Nodes auf dem gleichen Weg installiert, in der aktuellen Version 0.1.2 und als Gegenstelle einen AMTRON mit Software Version 1.13 benutzt.

Ich kann den Fehler aber beim besten Willen nicht nachstellen, auch nicht mit dem geposteten Flow. Nicht nur, dass Node-RED nicht abstürzt, der AMTRON führt die Befehle auch korrekt aus.

Deswegen kann ich dir gerade nur empfehlen einmal ein frisches Setup auszuprobieren, evtl. mal ohne andere Nodes zu installieren und auf jeden Fall ohne das Datenverzeichnis des alten Containers zu mounten.

**Comment by msob** [comment]
Wenn du das Experiment mit dem frischen Container machst und der Fehler noch auftritt, kannst du übrigend gerne mal die Logs und Fehlermeldungen posten, die Node-RED ausgibt.

**Comment by ecar2022** [comment]
So, habe etwas gebraucht. Die Node funktioniert mit Änderung der Leistung (0,6-16A) sehr gut! Bei PAUSE habe ich immer noch den gleichen Effekt. Kann aber mit der Lösung so nun gut leben.
Gibt es die Möglichkeit diese auch in der Raspberrymatic zu integrieren?

**Comment by msob** [comment]
Freut mich, dass du dir behelfen konntest, ich frage mich aber noch immer, warum die Pause-Funktion bei dir nicht funktioniert.

Ich kenne mich mit der Raspberrymatic nicht gut aus, aber [RedMatic](https://github.com/rdmtc/RedMatic) könnte das richtige für dich sein.
