### ISSUE TITLE
Amtron Professional - without "+"

### ISSUE THREAD

**Issue by gklank** [msob/NodeRedContribAmtronWallbox#2]
hi,

is there a possibility for an additional box?
I am using the Amtron Professional - the one which is not "Eichrechtskonform"...

Modbus is there...

Regards

Gerhard

**Comment by msob** [comment]
Hi Gerhard,
can you tell me which model you bought?
Maybe the Modelnumber?

**Comment by gklank** [comment]
Hi,

it is: MENNEKES AMTRON Professional PNC 22 C2, Nr. 1385202

Regards

Gerhard
P.S. just to inform you: the Box has an OCPP functionality as well. With that I got it into the node-red with the "@smappee/node-red-contrib-smappee-ev" nodes...

**Comment by msob** [comment]
Hi Gerhard,

yes, the AMTRON Professional ist another product line, like the AMTRON Charge Control, but with OCPP support.
Sadly MENNEKES changed the ModbusTCP interface in that product lineup, so my Node-Red node does not support them.

But I am glad to hear, you have found a working alternative! 

Best regards,
Markus
